### ISSUE TITLE
seg fault occurred...

### ISSUE THREAD

**Issue by moguriso** [moguriso/httpcmd#3]
goroutine 5 [running]:
module/sensortag.(*Data).getPage(0xc420060f90, 0xc420060f60, 0x2f)
        /home/adachi/repo/httpcmd/src/module/sensortag/button.go:60 +0x3a
module/sensortag.(*Data).getSensorData(0xc420060f90, 0x0, 0x0, 0x0, 0x0)
        /home/adachi/repo/httpcmd/src/module/sensortag/button.go:139 +0x311
module/sensortag.(*Data).ReadButtonThread(0xc420060f90)
        /home/adachi/repo/httpcmd/src/module/sensortag/button.go:158 +0xc0
created by main.main
        /home/adachi/repo/httpcmd/src/main/main.go:27 +0x1e4

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x686106]

goroutine 5 [running]:
module/sensortag.(*Data).getSensorData(0xc420060f90, 0x0, 0x0, 0x0, 0x0)
        /home/adachi/repo/httpcmd/src/module/sensortag/button.go:134 +0x86
module/sensortag.(*Data).ReadButtonThread(0xc420060f90)
        /home/adachi/repo/httpcmd/src/module/sensortag/button.go:158 +0xc0
created by main.main
        /home/adachi/repo/httpcmd/src/main/main.go:27 +0x1e4

**Comment by moguriso** [comment]
ああ、ちゃんとtrackしてあった。チャンと直そう。。。orz

**Comment by moguriso** [comment]
goroutine 5 [running]:
module/sensortag.(*Data).getSensorData(0xc420060f90, 0x0, 0x0, 0x0, 0x0)
    /home/adachi/repo/httpcmd/src/module/sensortag/button.go:134 +0x86
module/sensortag.(*Data).ReadButtonThread(0xc420060f90)
    /home/adachi/repo/httpcmd/src/module/sensortag/button.go:158 +0xc0
created by main.main
    /home/adachi/repo/httpcmd/src/main/main.go:27 +0x1e4
2017/12/04 10:47:03 camera index:  0
2017/12/04 10:47:03 sensor target URL:  http://xxxxxxxxxxxxxxxxxxxx
2017/12/04 10:47:03 sensor read interval:  1000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x686106]
